# Generated by Django 5.0.2 on 2024-02-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_paciente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, verbose_name=10),
        ),
    ]
