# Generated by Django 5.0.2 on 2024-02-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_paciente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
