# Generated by Django 5.0.2 on 2024-02-27 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_paciente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
