# Generated by Django 5.0.2 on 2024-02-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_paciente_cedula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
