# Generated by Django 5.0.2 on 2024-02-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen_disponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_examen',
            fields=[
                ('examen_disponible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.examen_disponible')),
                ('valor_resultado', models.FloatField(blank=True, null=True)),
                ('rango', models.CharField(blank=True, max_length=25, null=True)),
            ],
            bases=('home.examen_disponible',),
        ),
    ]
