# Generated by Django 5.0.2 on 2024-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_examen_disponible_resultado_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='resultados_examenes',
            field=models.ManyToManyField(related_name='pacientes', to='home.resultado_examen'),
        ),
    ]
