# Generated by Django 5.0.2 on 2024-02-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_paciente_resultados_examenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='resultados_examenes',
        ),
        migrations.CreateModel(
            name='Pedido_examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_examenes', to='home.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Resultado_examen',
        ),
    ]
