# Generated by Django 5.0.2 on 2024-02-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_paciente_resultados_examenes_pedido_examen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado_examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_resultado', models.FloatField(blank=True, null=True)),
                ('rango', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.examen_disponible')),
                ('pedido_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to='home.pedido_examen')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='resultados_examenes',
            field=models.ManyToManyField(related_name='pacientes', to='home.resultado_examen'),
        ),
    ]
