# Generated by Django 5.0.2 on 2024-02-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pedido_examen_pendiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='resultados_examenes',
        ),
        migrations.AddField(
            model_name='pedido_examen',
            name='examenes_disponibles',
            field=models.ManyToManyField(related_name='pedidos_examenes', to='home.examen_disponible'),
        ),
    ]
